services:
  web:
    image: nginx
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
    depends_on:
        - app1
        - app2
    networks:
        - redinha

  app1:
    build: ./backend/
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres
      - mongo
    networks:
      - redinha

  app2:
    build: ./backend/
    ports:
      - "8001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres
      - mongo
    networks:
      - redinha

  postgres:
    container_name: postgres
    image: postgres:17.4
    environment:
      POSTGRES_USER: tests
      POSTGRES_PASSWORD: test12345
      POSTGRES_DB: UsersDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - redinha

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - redinha

volumes:
  postgres_data:
  mongo_data:

networks:
  redinha:
